@startuml
!include style.puml

skinparam arrowColor #black
skinparam SequenceBoxBorderColor #black
skinparam SequenceParticipantBorderThickness 2
skinparam SequenceReferenceBorderThickness 2
skinparam DiagramBorderThickness 2
skinparam SequenceArrowThickness 2
skinparam SequenceLifeLineBorderColor #black
skinparam ParticipantBorderColor #black

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Storage" as storage STORAGE_COLOR

user -> ui : "delete 1"
activate ui UI_COLOR

ui -> logic : execute("delete 1")
activate logic LOGIC_COLOR

logic -> model : deleteTask(t)
activate model MODEL_COLOR

model --> logic
deactivate model

logic -> storage : saveStudyBuddy(studybuddy)
activate storage STORAGE_COLOR

storage -> storage : Save to file
activate storage STORAGE_COLOR_T1
deactivate storage

storage --> logic
deactivate storage

logic --> ui
deactivate logic

ui--> user
deactivate ui
@enduml
