@startuml
start
skinparam ActivityBackgroundColor #tan
skinparam ActivityBorderColor #black
skinparam activityDiamondBorderColor #black
skinparam activityDiamondBackgroundColor #tan
skinparam arrowColor #black

:User requests for a calendar;

label lab1
:User enters the date he wants for the calendar;


:Time parser parses the date;

if () then ([Selected date is within
50 years of current date])

:Calendar is generated;
:Tasks due on selected date is added to task panel;
else ([else])
:Error is thrown;
endif

:User sees calendar with all tasks on selected date;
stop
@enduml
