@startuml
start

skinparam ActivityBackgroundColor #tan
skinparam ActivityBorderColor #black
skinparam activityDiamondBorderColor #black
skinparam activityDiamondBackgroundColor #tan
skinparam arrowColor #black

:User executes refresh command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.
: Study Buddy traverses Due Soon list;

if () then ([task is Due Soon])
    if () then ([task is not present in Due Soon list])
        :Add task to Due Soon list;
    else ([else])
    endif
else ([else])
    if () then ([Due Soon list contains task])
        :Delete task from Due Soon list;
    else ([else])
    endif;
endif;
stop
@enduml
