@startuml
!include style.puml

skinparam arrowColor #black
skinparam SequenceBoxBorderColor #black
skinparam SequenceParticipantBorderThickness 2
skinparam SequenceReferenceBorderThickness 2
skinparam DiagramBorderThickness 2
skinparam SequenceArrowThickness 2
skinparam SequenceLifeLineBorderColor #black
skinparam ParticipantBorderColor #black


box UI UI_COLOR_T1
participant ":UI" as UI UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":RefreshTaskInteractivePrompt" as RefreshTaskInteractivePrompt LOGIC_COLOR
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":RefreshCommand" as RefreshCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":StudyBuddy" as StudyBuddy MODEL_COLOR
end box

UI-> RefreshTaskInteractivePrompt : execute(due soon)
activate RefreshTaskInteractivePrompt

RefreshTaskInteractivePrompt -> LogicManager : execute()
activate LogicManager

LogicManager -> RefreshCommand : execute()
activate RefreshCommand

RefreshCommand -> Model : addDueSoonTask()
activate Model

Model -> StudyBuddy : addDueSoonTask()
activate StudyBuddy

StudyBuddy --> Model
deactivate StudyBuddy

Model --> RefreshCommand
deactivate Model

RefreshCommand --> LogicManager
deactivate RefreshCommand
destroy RefreshCommand

LogicManager --> RefreshTaskInteractivePrompt
deactivate LogicManager

UI<--RefreshTaskInteractivePrompt
deactivate RefreshTaskInteractivePrompt
destroy RefreshTaskInteractivePrompt

@enduml
