@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR
skinparam classBorderColor #black

package Logic {

package InteractiveCommandParser {
Class TaskParser
Class TimeParser
Class StudyBuddyParser
}

package Command {
Class XYZCommand
Class CommandResult
Class "{abstract}\nCommand" as Command
}

Interface Logic <<Interface>>
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}


package Ui {
Class HiddenUi #FFFFFF
}

Ui .>InteractiveCommandParser : uses
Ui .>XYZCommand : creates
InteractiveCommandParser---[hidden]>XYZCommand

note right of XYZCommand: XYZCommand includes \nAddTaskCommand, \nFindTaskCommand, etc

Command .right.> Model
LogicManager -down-> Model

Model.[hidden].> LogicManager

TaskParser -[hidden]-> TimeParser
StudyBuddyParser -[hidden]-> TaskParser

XYZCommand .up.|> Command
LogicManager .up.|> Logic



Logic ..> CommandResult
LogicManager .down.> CommandResult : executes
Command .up.> CommandResult





@enduml
