@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR
skinparam classBorderColor #black

package Logic {

package Parser {
Class TaskParser
Class TimeParser
Class StudyBuddyParser
}

package Command {
Class XYZCommand
Class CommandResult
Class "{abstract}\nCommand" as Command
}

package InteractivePrompt {
Class XYZInteractivePrompt
}

Interface Logic <<Interface>>
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}

XYZInteractivePrompt .>Parser : uses
XYZInteractivePrompt .>XYZCommand : creates

Command .right.> Model
LogicManager -down-> Model

Model.[hidden].> LogicManager



XYZCommand .up.|> Command
LogicManager .up.|> Logic



Logic ..> CommandResult
LogicManager .down> CommandResult : executes
Command .up.> CommandResult


note right of XYZInteractivePrompt: XYZInteractivePrompt includes \nAddTaskInteractivePrompt, \nFindTaskInteractivePrompt, etc.\n\nSimilarly,\nXYZCommand includes \nAddTaskCommand, \nFindTaskCommand, etc.


@enduml
