@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classBorderColor #black
skinparam arrowColor #black

Package Model <<Rectangle>>{
Interface ReadOnlyStudyBuddy <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class StudyBuddy
Class ReadOnlyStudyBuddy
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Task {
Class UniqueTaskList
Class Task
Enum TaskStatus
Enum TaskType
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

StudyBuddy .up.|> ReadOnlyStudyBuddy

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" StudyBuddy
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

StudyBuddy *--> "1" UniqueTaskList

UniqueTaskList o-> "*" Task
Task *--> TaskStatus
Task *--> TaskType

Task *--> "*" Tag

ModelManager -->"1" Task : filtered list
@enduml

