@startuml
!include style.puml

skinparam arrowColor #black
skinparam SequenceBoxBorderColor #black
skinparam SequenceParticipantBorderThickness 2
skinparam SequenceReferenceBorderThickness 2
skinparam DiagramBorderThickness 2
skinparam SequenceArrowThickness 2
skinparam SequenceLifeLineBorderColor #black
skinparam ParticipantBorderColor #black

actor User

participant ":UI" as UI UI_COLOR
participant ":Logic" as Logic UI_COLOR
participant ":Model" as Model UI_COLOR

User -> UI : interact(new data)
activate UI

UI -> Logic : executeCommand(updateCommand)
activate Logic
note right UI_COLOR_NOTE: <b>updateCommand</b>\n can be add, edit, delete etc. \ncommands

Logic -> Model : saveStudyBuddy(updated StudyBuddy)
deactivate Logic
activate Model


Model -> Model : saveStudyBuddy(updated StudyBuddy)
activate Model
deactivate Model
deactivate Model

UI -> UI : render()
note right UI_COLOR_NOTE: the UI detects module change \nand renders automatically
activate UI
deactivate UI
UI --> User: show latest statistics
deactivate UI
@enduml
