@startuml
!include style.puml

skinparam DiagramBorderThickness 2
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR
skinparam classBorderColor #black


package UI <<Rectangle>>{
Class XYZPanel
Class XYZCard
Class CommandBox
CLass FeedbackDisplayBox
Class MainWindow
Class StatusBarFooter
Interface Ui <<Interface>>
Class UiManager
Class "{abstract}\nUiPart" as UiPart
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}


UiManager .left.|> Ui


UiManager -down-> MainWindow
MainWindow *-down-> StatusBarFooter
MainWindow *-down-> CommandBox
MainWindow *-down-> FeedbackDisplayBox
MainWindow *-down-> XYZPanel
XYZPanel *-down-> XYZCard


StatusBarFooter -right[hidden]- FeedbackDisplayBox
MainWindow -down[hidden]- UiManager


MainWindow -left-|> UiPart
XYZCard --|> UiPart
XYZPanel --|> UiPart
CommandBox --|> UiPart
FeedbackDisplayBox --|> UiPart
StatusBarFooter --|> UiPart


XYZCard ..> Model
XYZPanel ..> Model


UiManager -right-> Logic
MainWindow -left-> Logic
CommandBox -left-> Logic

CommandBox -left[hidden]- FeedbackDisplayBox
MainWindow -down[hidden]- UiPart

note right of XYZPanel UI_COLOR_NOTE
<b>XYZPanel</b> = CalendarPanel,
DueSoonListPanel, ModuleListPanel,
ProductivityPanel, TaskListPanel,
TaskSummaryPanel
end note

note right of XYZCard UI_COLOR_NOTE
<b>XYZCard</b> = DetailedTaskCard,
DueSoonTaskCard, ModCard
end note

note "The <b>HiddenLogic</b> and <b>HiddenModel</b> \nrepresent the less important details \nfrom <b>Logic</b> and <b>Model</b> components" as N1 UI_COLOR_NOTE


@enduml
