@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":DueSoonTaskInteractivePrompt" as DueSoonTaskInteractivePrompt UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StudyBuddyParser" as StudyBuddyParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedStudyBuddy" as VersionedStudyBuddy MODEL_COLOR
end box

[-> DueSoonTaskInteractivePrompt : execute(due soon)
activate DueSoonTaskInteractivePrompt

DueSoonTaskInteractivePrompt -> LogicManager : execute()

LogicManager -> StudyBuddyParser : parseCommand(undo)
activate StudyBuddyParser

create UndoCommand
StudyBuddyParser -> UndoCommand
activate UndoCommand

UndoCommand --> StudyBuddyParser
deactivate UndoCommand

StudyBuddyParser --> LogicManager : u
deactivate StudyBuddyParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoStudyBuddy()
activate Model

Model -> VersionedStudyBuddy : undo()
activate VersionedStudyBuddy

VersionedStudyBuddy -> VersionedStudyBuddy :resetData(ReadOnlyStudyBuddy)
VersionedStudyBuddy --> Model :
deactivate VersionedStudyBuddy

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
