= Huang ge xiang - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Study Buddy

== Overview

StudyBuddy is a desktop application designed for students who *wish to manage their module related tasks* in a convenient and user-friendly interface.
It is *optimized for those who prefer to work with a Command Line Interface* (CLI) but still contains the benefits of *Graphical User Interface* (GUI) which was written using JavaFX.
The codebase is in Java and contains about 13kLoc.

== Summary of contributions

=== Enhancements

*Major enchancements*

* Added a *calendar* to Study buddy.
** What it does:
*** The calendar allows users to have an overview of all the tasks that has to be done.
*** Calendar also allows you to view all tasks due on the day the user clicks on.
** Justification:
*** This feature is important as the task list will be too cluttered without it.
*** A calendar gives a good indication of how busy the user is going to be.
*** It is also a good way to filter tasks by date.
** Highlights:
***

*Major enhancement*

=== User guide
=== Developer Guide
=== Team-based Tasks
* Helped set up the github team and repo.
* Assigned issues to some of my team members.
* Left constructive feedback on some of my team member's pull request.
* Helped resolve some issues my team mates had regarding address book 3.
* Created tests for classes that were not mine.

=== Review/Mentoring
* Left feedback