:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

=== [teal]#*Soumwyaa Sabarinathann - Project Portfolio*#

[teal]#*Project: Study Buddy*#

[teal]#*Overview*#

StudyBuddy is a desktop application designed for students who *wish to manage their module related tasks* in a convenient and user-friendly interface. The application is written in Java and spans over 12k lines of code.

[teal]#*Summary of contributions*#

* *Major enhancement*: added *the Due Soon List feature*
** Function:
It allows users to view a list of tasks due within the next week in one panel. It also displays time left before the deadline for each due soon task, auto-sorts tasks to be in order of most urgent to least urgent deadline and auto-updates when changes are made to the data (additions, deletions, edits etc). +
It also provides a refresh command that is used to update the due soon list so it doesn't become invalid after a certain duration of time.
** Justification:
Helpful to the user because it reminds them of upcoming deadlines.
** Highlights:
This implementation was challenging because it required changes to be made to every command that changed data. It involved working in the logic, model, storage and UI components of the code base. It also involved changing the GUI.

* *Major enhancement*: added *the Add Duplicate Tasks feature*
** Function:
It allows users to add duplicate tasks by automatically appending brackets with a number to its task name. The number corresponds to the number of times task has been duplicated.
** Justification:
If the user makes a mistake in one field while adding task, they will have to re-enter all 12 fields if duplicates are not allowed.
** Highlights:
It required working on other commands, such as edit command and unarchive command to prevent duplication. Since study buddy already had a lot of checks to prevent duplicate tasks, it required a large amount of refactoring code.

* *Minor enhancement*: added *the Delete Task command*
** Function: Allows user to delete an existing task in the list
** Justification: Helpful to the user because it enables them to remove tasks from their list.

* *Minor enhancement*: added *the Filter command*
** Function: Allows user to filter by status (eg: finished, pending etc) or by type (eg: assignment, quiz etc)
** Justification: This feature is extremely helpful to the user because it enables them to filter their list of all tasks by various categories.

[teal]#*Code contributed:*# +
https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#=undefined&search=souwmyaa

[teal]#*Team-based Tasks*# +
1. Refactored all occurrences of Address Book to Study Buddy. Link to Pull Request https://github.com/AY1920S2-CS2103T-W16-3/main/pull/135[#135] +
2. Helped to maintain the issue tracker. Links to issues https://github.com/AY1920S2-CS2103T-W16-3/main/issues/283[#283], https://github.com/AY1920S2-CS2103T-W16-3/main/issues/268[#268]. +
3. Attempted to find bugs in all team members code to help them fix any issues. Links to issues https://github.com/AY1920S2-CS2103T-W16-3/main/issues/107[#107], https://github.com/AY1920S2-CS2103T-W16-3/main/issues/256[#256] +
4. Wrote test cases for error-prone classes, even if they were not mine. Links to Pull Requests https://github.com/AY1920S2-CS2103T-W16-3/main/pull/166[#166], https://github.com/AY1920S2-CS2103T-W16-3/main/pull/139[#139] +
5. Contributed to the forum. Link to issue https://github.com/nus-cs2103-AY1920S2/forum/issues/75[#75]

[teal]#*Review/Mentoring*# +
1. Reviewed other members Pull Requests. Links to Pull Requests https://github.com/AY1920S2-CS2103T-W16-3/main/pull/59[#59], https://github.com/AY1920S2-CS2103T-W16-3/main/pull/279[#279] +
2. Reviewed another team's DG and provided useful feedback. Links to issues https://github.com/AY1920S2-CS2103T-W17-3/main/issues/208[#208], https://github.com/AY1920S2-CS2103T-W17-3/main/issues/204[#204]

[teal]#*User guide*#

|===
|_Given below is a section that I contributed to the User Guide. It showcases my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

[teal]#*Developer Guide*#

|===
|_Given below are some sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=dueSoon]
include::../DeveloperGuide.adoc[tag=refresh]

Diagrams: +
https://github.com/AY1920S2-CS2103T-W16-3/main/blob/master/docs/diagrams/ModelClassDiagram.puml[Model class diagram] +
https://github.com/AY1920S2-CS2103T-W16-3/main/blob/master/docs/diagrams/DueSoonActivityDiagram.puml[Due soon activity diagram] +
https://github.com/AY1920S2-CS2103T-W16-3/main/blob/master/docs/diagrams/DueSoonSequenceDiagram.puml[Due soon sequence diagram] +
https://github.com/AY1920S2-CS2103T-W16-3/main/blob/master/docs/diagrams/AddDueSoonActivityDiagram.puml[Add due soon task activity diagram] +
https://github.com/AY1920S2-CS2103T-W16-3/main/blob/master/docs/diagrams/AddDueSoonSequence.puml[Add due soon task sequence diagram] +
https://github.com/AY1920S2-CS2103T-W16-3/main/blob/master/docs/diagrams/DeleteDueSoonActivityDiagram.puml[Delete due soon task activity diagram] +
https://github.com/AY1920S2-CS2103T-W16-3/main/blob/master/docs/diagrams/DeleteDueSoonSequence.puml[Delete due soon task sequence diagram]


